<?php

namespace Tests\Feature;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Group;
use Tests\TestCase;

/**
 * @group Feature: dual-qr-pdf-stamping, Property 10: QR Code URL Encoding
 */
#[Group('Feature: dual-qr-pdf-stamping, Property 10: QR Code URL Encoding')]
class QrCodeUrlEncodingPropertyTest extends TestCase
{
    /**
     * Validates: Requirements 5.4
     *
     * Property 10: QR Code URL Encoding
     * For any document with document_number N, the QR code generated by the "Cetak QR Code"
     * action SHALL encode exactly the URL {APP_URL}/dokumen/aktif/{N}.
     */
    #[DataProvider('randomDocumentNumberProvider')]
    public function test_qr_code_url_matches_expected_format(string $documentNumber): void
    {
        $appUrl = config('app.url');

        // Construct URL using the same logic as DocumentResource Cetak QR Code action
        $encodedUrl = $appUrl . '/dokumen/aktif/' . $documentNumber;

        // Verify the URL matches the expected pattern exactly
        $expectedUrl = config('app.url') . '/dokumen/aktif/' . $documentNumber;
        $this->assertSame($expectedUrl, $encodedUrl);

        // Verify URL structure components
        $this->assertStringStartsWith($appUrl . '/dokumen/aktif/', $encodedUrl);
        $this->assertStringEndsWith($documentNumber, $encodedUrl);

        // Verify the document_number appears exactly once in the URL path
        $path = parse_url($encodedUrl, PHP_URL_PATH);
        $this->assertSame('/dokumen/aktif/' . $documentNumber, $path);

        // Verify no double slashes in path (except protocol)
        $urlWithoutProtocol = preg_replace('#^https?://#', '', $encodedUrl);
        $this->assertStringNotContainsString('//', $urlWithoutProtocol);
    }

    /**
     * Validates: Requirements 5.4
     *
     * Property 10: QR Code URL Encoding
     * Verify that the URL uses config('app.url') for the base, not a hardcoded value.
     */
    #[DataProvider('randomDocumentNumberProvider')]
    public function test_qr_code_url_uses_app_config_base(string $documentNumber): void
    {
        $appUrl = config('app.url');

        // The URL must start with the configured APP_URL
        $encodedUrl = $appUrl . '/dokumen/aktif/' . $documentNumber;

        $this->assertStringStartsWith($appUrl, $encodedUrl);

        // Verify the route segment is exactly '/dokumen/aktif/{document_number}'
        $routeSegment = str_replace($appUrl, '', $encodedUrl);
        $this->assertSame('/dokumen/aktif/' . $documentNumber, $routeSegment);
    }

    /**
     * Validates: Requirements 5.4
     *
     * Property 10: QR Code URL Encoding
     * Verify various document_number formats produce valid URLs.
     */
    #[DataProvider('variousDocumentNumberFormatsProvider')]
    public function test_various_document_number_formats_produce_valid_url(string $documentNumber): void
    {
        $appUrl = config('app.url');

        $encodedUrl = $appUrl . '/dokumen/aktif/' . $documentNumber;

        // Verify exact match with expected format
        $expected = sprintf('%s/dokumen/aktif/%s', $appUrl, $documentNumber);
        $this->assertSame($expected, $encodedUrl);

        // Verify the URL is well-formed (has scheme, host, and path)
        $parsedUrl = parse_url($encodedUrl);
        $this->assertNotFalse($parsedUrl);
        $this->assertArrayHasKey('scheme', $parsedUrl);
        $this->assertArrayHasKey('host', $parsedUrl);
        $this->assertArrayHasKey('path', $parsedUrl);
    }

    /**
     * Generate 110+ random document_number values using Faker.
     */
    public static function randomDocumentNumberProvider(): iterable
    {
        $faker = \Faker\Factory::create('id_ID');

        for ($i = 0; $i < 110; $i++) {
            $prefix = $faker->randomElement(['GSR', 'DOC', 'SOP', 'WI', 'FM', 'IK']);
            $number = $faker->numerify('###');
            $documentNumber = $prefix . '-' . $number;

            yield "doc_number_{$i}" => [$documentNumber];
        }
    }

    /**
     * Generate document_number values in various formats that might be encountered.
     */
    public static function variousDocumentNumberFormatsProvider(): iterable
    {
        $faker = \Faker\Factory::create('id_ID');

        // Specific format patterns
        $patterns = [
            'GSR-001',
            'DOC-2024-001',
            'SOP-LAB-001',
            'WI-QC-2024-005',
            'FM-HRD-010',
            'IK-PROD-003',
            'GSR-001-A',
            'DOC-2024-001-REV01',
            'SOP-001.01',
            'WI-001-2024',
        ];

        foreach ($patterns as $idx => $pattern) {
            yield "format_pattern_{$idx}" => [$pattern];
        }

        // Generate additional random formats
        for ($i = 0; $i < 100; $i++) {
            $prefix = $faker->randomElement(['GSR', 'DOC', 'SOP', 'WI', 'FM', 'IK']);
            $separator = $faker->randomElement(['-', '-']);
            $year = $faker->optional(0.3)->randomElement(['2023', '2024', '2025']);
            $number = $faker->numerify('###');
            $suffix = $faker->optional(0.2)->randomElement(['-A', '-B', '-REV01', '-REV02']);

            $documentNumber = $prefix . $separator . ($year ? $year . $separator : '') . $number . ($suffix ?? '');

            yield "random_format_{$i}" => [$documentNumber];
        }
    }
}
